### ISSUE TITLE
CLEARTEXT communication to camera not permitted by network security policy

### ISSUE THREAD

**Issue by sayan-futurehook** [speedfox-uk/IpCameraIntercom#1]
![Screenshot 2022-11-22 at 12 41 06 PM](https://user-images.githubusercontent.com/110037874/203248517-d03c2567-6e83-4fc2-8384-e5df29090730.png)

**Comment by sayan-futurehook** [comment]
Needed to add IP of camera in network_security_config.xml

**Comment by speedfox-uk** [comment]
Thanks for pointing this out. I've updated the README with a note on that.

**Comment by speedfox-uk** [comment]
Just want to know: What camera are you using? I just want to add it to the list of cameras that are known to work with this app.
